In [1]:
from itertools import product
import numpy as np

In [18]:
def v (n, q):
    """construct a linear space of dimension n over a finite field of order q"""
    return [''.join(str(pos) for pos in comb) for comb in list(product(range(q), repeat=n))]

---

__Exercise 7.6__
Let $C$ be the ternary linear code with generator matrix
$$
\begin{bmatrix}
1 & 1 & 1 & 0\\
2 & 0 & 1 & 1
\end{bmatrix}
\text{.}
$$
(a) Find a generator matrix for $C$ in standard form.<br>
(b) Find a parity-check matrix for $C$ in standard form.<br>
(c) Use syndrome decoding to decode the received vectors $2121$, $1201$, and $2222$.

---

Theorem 5.5 (Standard-Form Generator Matrix Procedure)

$$
\begin{bmatrix}
1 & 1 & 1 & 0\\
2 & 0 & 1 & 1
\end{bmatrix}
\rightarrow
\begin{bmatrix}
1 & 1 & 1 & 0\\
0 & 1 & 2 & 1
\end{bmatrix}
\rightarrow
\begin{bmatrix}
1 & 0 & 2 & 2\\
0 & 1 & 2 & 1
\end{bmatrix}
$$

$\mathbf{u}G = \mathbf{x}$

$$
\begin{bmatrix}
0 & 0\\
0 & 1\\
0 & 2\\
1 & 0\\
1 & 1\\
1 & 2\\
2 & 0\\
2 & 1\\
2 & 2\\
\end{bmatrix}
\begin{bmatrix}
1 & 0 & 2 & 2\\
0 & 1 & 2 & 1
\end{bmatrix}
=
\begin{bmatrix}
0 & 0 & 0 & 0\\
0 & 1 & 2 & 1\\
0 & 2 & 1 & 2\\
1 & 1 & 1 & 0\\
1 & 2 & 0 & 1\\
2 & 0 & 1 & 1\\
2 & 1 & 0 & 2\\
2 & 2 & 2 & 0\\
\end{bmatrix}
$$

Theorem 7.6 (Standard-Form Parity-Check Matrix from Standard-Form Generator Matrix)

\begin{bmatrix}
1 & 1 & 1 & 0\\
1 & 2 & 0 & 1
\end{bmatrix}

In [21]:
n = 2
q = 3
messages = np.array([list(i) for i in v(n, q)], dtype=int)
generator = np.array([['1', '0', '2', '2'], ['0', '1', '2', '1']], dtype=int)
code = np.mod(np.dot(messages, generator), q)

print('Messages')
print(messages)
print()
print('Standard-Form Generator')
print(generator)
print()
print('Code')
print(code)

Messages
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]

Standard-Form Generator
[[1 0 2 2]
 [0 1 2 1]]

Code
[[0 0 0 0]
 [0 1 2 1]
 [0 2 1 2]
 [1 0 2 2]
 [1 1 1 0]
 [1 2 0 1]
 [2 0 1 1]
 [2 1 0 2]
 [2 2 2 0]]


---

__Exercise 7.7__
Using the code of Example 7.12, decode the received vector $0617960587$.

---

__Exercise 7.10__
Suppose a certain binary channel accepts words of length 7 and that the only kind of error vector ever observed is one of the eight vectors $0000000$, $0000001$, $0000011$, $0000111$, $0001111$, $0011111$, $0111111$, $1111111$. Design a binary linear $[7, k]$-code which will correct all such errors with as large a rate as possible.

---